package introsde.assignment.soap;

import introsde.document.model.HealthMeasureHistory;
import introsde.document.model.LifeStatus;
import introsde.document.model.MeasureDefinition;
import introsde.document.model.Person;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.jws.soap.SOAPBinding.Use;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService
@SOAPBinding(style = Style.DOCUMENT, use=Use.LITERAL) //optional
public interface People {

	// Method #1: readPersonList() => List
	@WebMethod(operationName = "readPersonList")
	@WebResult(name = "people")
	public List<Person> getPeople();

	// Method #2: readPerson(Long id) => Person
	@WebMethod(operationName = "readPerson")
	@WebResult(name = "person")
	public Person readPerson(@WebParam(name = "personId") Long id);

	// Method #3: updatePerson(Person p) => Person
	@WebMethod(operationName = "updatePerson")
	@WebResult(name = "personId")
	public Person updatePerson(@WebParam(name = "person") Person person);

	// Method #4: createPerson(Person p) => Person
	@WebMethod(operationName = "createPerson")
	@WebResult(name = "personId")
	public Person createPerson(@WebParam(name = "person") Person person);

	// Method #5: deletePerson(Long id)
	@WebMethod(operationName = "deletePerson")
	@WebResult(name = "personId")
	public boolean deletePerson(@WebParam(name = "personId") Long id);

	// Method #6: readPersonHistory(Long id, String measureType) => List
	@WebMethod(operationName = "readPersonHistory")
	@WebResult(name = "HealthMeasureHistory")
	public List<HealthMeasureHistory> readPersonHistory(
			@WebParam(name = "personId") Long id,
			@WebParam(name = "measureType") String measureType);

	// Method #7: readMeasureTypes() => List
	@WebMethod(operationName = "readMeasureTypes")
	@WebResult(name = "MeasureDefinition")
	public List<MeasureDefinition> readMeasureTypes();

	// Method #8: readPersonMeasure(Long id, String measureType, Long mid) =>
	// Measure
	@WebMethod(operationName = "readPersonMeasure")
	@WebResult(name = "HealthMeasureHistory")
	public HealthMeasureHistory readPersonMeasure(
			@WebParam(name = "personId") Long id,
			@WebParam(name = "measureType") String measureType,
			@WebParam(name = "mid") Long mid);

	// Method #9: savePersonMeasure(Long id, Measure m) => LifeStatus
	@WebMethod(operationName = "savePersonMeasure")
	@WebResult(name = "LifeStatus")
	public LifeStatus savePersonMeasure(@WebParam(name = "personId") Long id,
			@WebParam(name = "lifestatus") LifeStatus m);

	// Method #10: updatePersonMeasure(Long id, Measure m) => Measure
	@WebMethod(operationName = "updatePersonMeasure")
	@WebResult(name = "HealthMeasureHistory")
	public HealthMeasureHistory updatePersonMeasure(
			@WebParam(name = "personId") Long id,
			@WebParam(name = "lifestatus") HealthMeasureHistory m);
}
